# Generated by Django 3.0.2 on 2020-01-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erp',
            name='ph',
            field=models.CharField(max_length=100),
        ),
    ]
